export const NEWARRIVALITEMS_DETAILS_REQUEST = 'NEWARRIVALITEMS_DETAILS_REQUEST'
export const NEWARRIVALITEMS_DETAILS_SUCCESS = 'NEWARRIVALITEMS_DETAILS_SUCCESS'
export const NEWARRIVALITEMS_DETAILS_FAIL = 'NEWARRIVALITEMS_DETAILS_FAIL'
