export const products_0 = [
  {
    _id: '1',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/tee_images/IMG_0914.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Vintage Harajuku sweatshirt-Women',
    image: '/sweatshirt_images/IMG_0924.JPG',
    texture: '100% cotton fabric',
    weight: '230g weight',
    description: 'Please choose one size up as these run small',
    category: 'Sweatshirt',
    price: 9000,
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 32,
    rating: 4.5,
    numReviews: 12,
  },
]
export const teesItems = [
  {
    _id: '1',
    name: 'Smile graphics T-Shirt',
    image: '/tee_images/IMG_0844.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'smile-grapgics-t-shirt',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '9,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 32,
  },
  {
    _id: '2',
    name: 'Mens short-sleeve equilibrum T-shirt',
    image: '/tee_images/IMG_0846.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    linkName: 'mens-short-sleeve-equilibrum-t-shirt',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '7,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 27,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Guys letter Tee',
    image: '/tee_images/IMG_0847.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small ',
    brand: 'Cannon',
    category: 'Tees',
    linkName: 'guys-letter-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '8,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "Men's cactus & letter graphic tee",
    image: '/tee_images/IMG_0848.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'mens-cactus-&-letter-graphic-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '8,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Vintage cherub graphic tee',
    image: '/tee_images/IMG_0849.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'vintage-cherub-graphic-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '7,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Faded Grey Tee',
    image: '/tee_images/IMG_0850.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small ',
    category: 'Tees',
    linkName: 'faded-grey-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '9,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 20,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Designer Tee',
    image: '/tee_images/IMG_0851.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'designer-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '10,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 17,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Peace Sign embroidery tee',
    image: '/tee_images/IMG_0852.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'peace-sign-embroidery-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '7,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 15,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Forward Embroidery tee',
    image: '/tee_images/IMG_0853.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'forward-embroidery-tee',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '7,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Embroidery tee With Text',
    image: '/tee_images/IMG_0854.JPG',
    texture: '100% cotton fabric',
    description: 'Please choose one size up as these run small',
    category: 'Tees',
    linkName: 'embroidery-tee-with-text',
    desc_texture: '100% cotton fabric',
    desc_weight: '230g weight',
    desc_info: 'Please choose one size up as these run small',
    price: '8,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 12,
    rating: 4,
    numReviews: 12,
  },
]
export const footwearItems = [
  {
    _id: '1',
    name: "Men's Toga Pulla Suede Buckle Strap Mules Brown",
    image: '/footwear_images/IMG_2041.JPG',
    category: 'Footwears',
    linkName: 'mens-toga-pulla-suede-buckle-strap-mules-brown',
    price: '25,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Canvas Sneaker',
    image: '/footwear_images/IMG_1944.JPG',
    category: 'Footwears',
    linkName: 'canvas-sneaker',
    price: '36,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Air Jordan 1',
    image: '/footwear_images/IMG_1943.JPG',
    category: 'Footwears',
    linkName: 'air-jordan-1',
    price: '57,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Wild Sand Knit Runner',
    image: '/footwear_images/IMG_0820.JPG',
    category: 'Footwears',
    linkName: 'wild-sand-knit-runner',
    price: '27,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Nike Air Barrage",
    image: '/footwear_images/IMG_0821.JPG',
    category: 'Footwears',
    linkName: 'mens-nike-air-barrage',
    price: '37,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Nike Air Mag 'Grey Mag'",
    image: '/footwear_images/IMG_0823.JPG',
    category: 'Footwears',
    linkName: 'nike-air-mag-grey-mag',
    price: '45,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Air More Uptempo 'Black White'",
    image: '/footwear_images/IMG_0824.JPG',
    category: 'Footwears',
    linkName: 'air-more-uptempo-black-white',
    price: '65,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Trainers Sneakers Shoe',
    image: '/footwear_images/IMG_0825.JPG',
    category: 'Footwears',
    linkName: 'trainers-sneakers-shoe',
    price: '30,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Lace Up Chunky Shoes',
    image: '/footwear_images/IMG_0826.JPG',
    category: 'Footwears',
    linkName: 'lace-up-chunky-shoes',
    price: '22,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Versace Black Leather Sandals',
    image: '/footwear_images/IMG_0827.JPG',
    category: 'Footwears',
    linkName: 'versace-black-leather-sandals',
    price: '19,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 13,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Arizona Soft Slide Sandal',
    image: '/footwear_images/IMG_0828.JPG',
    category: 'Footwears',
    linkName: 'arizona-soft-slide-sandal',
    price: '13,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'Lightweight Casual Shoes',
    image: '/footwear_images/IMG_0818.JPG',
    category: 'Footwears',
    linkName: 'lightweight-casual-shoes',
    price: '20,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Custom Nike Airforce 1',
    image: '/footwear_images/IMG_1946.JPG',
    category: 'Footwears',
    linkName: 'custom-nike-airforce-1',
    price: '33,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Barklay Canvas Plain Toe Oxford',
    image: '/footwear_images/IMG_1949.JPG',
    category: 'Footwears',
    linkName: 'barklay-canvas-plain-toe-oxford',
    price: '22,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Non-Slip EVA Flip Flops',
    image: '/footwear_images/IMG_1951.JPG',
    category: 'Footwears',
    linkName: 'non-slip-eva-flip-flops',
    price: '17,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
]
export const knitwearItems = [
  {
    _id: '1',
    name: 'Vintage Knitwear',
    image: '/knitwear_images/IMG_1952.JPG',
    category: 'Knitwears',
    linkName: 'vintage-knitwear',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '17,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Knitwear Item Patchwork',
    image: '/knitwear_images/IMG_1953.JPG',
    category: 'Knitwears',
    linkName: 'knitwear-item-patchwork',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Knitted Cardigan Deep Grey',
    image: '/knitwear_images/IMG_1954.JPG',
    category: 'Knitwears',
    linkName: 'knitted-cardigan-deep-grey',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '25,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Knitted Sweater Stripe White With V-neckline',
    image: '/knitwear_images/IMG_1956.JPG',
    category: 'Knitwears',
    linkName: 'knitted-sweater-stripe-white-with-v-neckline',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '25,200',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Knitted Sweater Turtleneck Deep Grey',
    image: '/knitwear_images/IMG_1957.JPG',
    category: 'Knitwears',
    linkName: 'knitted-sweater-turtleneck-deep-grey',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '12,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Knitted Cardigan Light Pink With Round Neckline',
    image: '/knitwear_images/IMG_1959.JPG',
    category: 'Knitwears',
    linkName: 'knitted-cardigan-light-pink-with-round-neckline',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Fancy Knitted Sweater',
    image: '/knitwear_images/IMG_1960.JPG',
    category: 'Knitwears',
    linkName: 'fancy-knitted-sweater',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '15,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Knitted Sweater Spiral Patchwork Color',
    image: '/knitwear_images/IMG_1961.JPG',
    category: 'Knitwears',
    linkName: 'knitted-sweater-spiral-patchwork-color',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '20,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Knitted Cardigan With Horizontal Stripe Color',
    image: '/knitwear_images/IMG_1962.JPG',
    category: 'Knitwears',
    linkName: 'knitted-cardigan-with-horizontal-stripe-color',
    description:
      'Made with quality , malleable wool, this range of knitwear is great for daily and occasional wear.',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
]
export const hoodiesItems = [
  {
    _id: '1',
    name: 'Winter Fleece Anime Sweatshirt',
    image: '/hoodies_images/IMG_0829.JPG',
    category: 'Hoodies',
    linkName: 'winter-fleece-anime-sweatshirt',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '17,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Layered Hoodie',
    image: '/hoodies_images/IMG_0830.JPG',
    category: 'Hoodies',
    linkName: 'layered-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Black Nylon Color Block Hoodie',
    image: '/hoodies_images/IMG_0831.JPG',
    category: 'Hoodies',
    linkName: 'black-nylon-color-block-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'White Hoodie',
    image: '/hoodies_images/IMG_0832.JPG',
    category: 'Hoodies',
    linkName: 'white-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,200',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'White Hoodie With Rose Design',
    image: '/hoodies_images/IMG_0833.JPG',
    category: 'Hoodies',
    linkName: 'white-hoodie-with-rose-design',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '12,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Black Grey Hoodie',
    image: '/hoodies_images/IMG_0834.JPG',
    category: 'Hoodies',
    linkName: 'black-grey-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Green Fancy Hoodie',
    image: '/hoodies_images/IMG_0835.JPG',
    category: 'Hoodies',
    linkName: 'green-fancy-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Purple With Black Hoodie Sweatshirt',
    image: '/hoodies_images/IMG_0836.JPG',
    category: 'Hoodies',
    linkName: 'purple-with-black-hoodie-sweatshirt',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '20,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Black Hoodie With Red Rose Design',
    image: '/hoodies_images/IMG_0837.JPG',
    category: 'Hoodies',
    linkName: 'black-hoodie-with-red-rose-design',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: "Men's Crazy Patch Detail With White Hoodie",
    image: '/hoodies_images/IMG_0838.JPG',
    category: 'Hoodies',
    linkName: 'mens-crazy-patch-detail-with-white-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 6,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: "Men's Designer Hoodie",
    image: '/hoodies_images/IMG_0839.JPG',
    category: 'Hoodies',
    linkName: 'mens-designer-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: "Fancy Men's Designer Hoodie",
    image: '/hoodies_images/IMG_0840.JPG',
    category: 'Hoodies',
    linkName: 'fancy-mens-designer-hoodie',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Essentials Hoodie Sweatshirt',
    image: '/hoodies_images/IMG_0841.JPG',
    category: 'Hoodies',
    linkName: 'essentials-hoodie-sweatshirt',
    desc_1: '100% Cotton',
    desc_2: 'Wool inner fleece',
    desc_3: 'Comfortable & lightweight',
    price: '15,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 13,
    rating: 4,
    numReviews: 12,
  },
]
export const capItems = [
  {
    _id: '1',
    name: 'Brown Baseball Cap',
    image: '/cap_images/IMG_0774.JPG',
    category: 'Caps',
    linkName: 'brown-baseball-cap',
    price: '7,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'City Of Angels A-Frame Snapback',
    image: '/cap_images/IMG_0775.JPG',
    category: 'Caps',
    linkName: 'city-of-angels-a-frame-snapback',
    price: '3,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Letter Embroidered Baseball Cap',
    image: '/cap_images/IMG_0776.JPG',
    category: 'Caps',
    linkName: 'letter-embroidered-baseball-cap',
    price: '5,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "Men's NY Yankees Cap",
    image: '/cap_images/IMG_0777.JPG',
    category: 'Caps',
    linkName: 'mens-ny-yankees-cap',
    price: '5,200',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'LA Snapback Baseball Cap',
    image: '/cap_images/IMG_0778.JPG',
    category: 'Caps',
    linkName: 'la-snapback-baseball-cap',
    price: '2,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Men's Green Oakland Cap",
    image: '/cap_images/IMG_0779.JPG',
    category: 'Caps',
    linkName: 'mens-green-oakland-cap',
    price: '3,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Fancy Designer Cap',
    image: '/cap_images/IMG_0780.JPG',
    category: 'Caps',
    linkName: 'fancy-designer-cap',
    price: '5,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Letter Graphic Baseball Cap',
    image: '/cap_images/IMG_0781.JPG',
    category: 'Caps',
    linkName: 'letter-graphic-baseball-cap',
    price: '3,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: "Women's Bucket Hat With Rings",
    image: '/cap_images/IMG_0782.JPG',
    category: 'Caps',
    linkName: 'womens-bucket-hat-with-rings',
    price: '5,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Peace Hand Baseball Hat',
    image: '/cap_images/IMG_0784.JPG',
    category: 'Caps',
    linkName: 'peace-hand-baseball-hat',
    price: '5,100',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: "Men's Chicago White Sox New Era Black Cap",
    image: '/cap_images/IMG_0786.JPG',
    category: 'Caps',
    linkName: 'mens-chicago-white-sox-new-era-black-cap',
    price: '5,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: 'The Punisher Hat',
    image: '/cap_images/IMG_0787.JPG',
    category: 'Caps',
    linkName: 'the-punisher-hat',
    price: '5,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: 'Fancy Crazy Faded Cap',
    image: '/cap_images/IMG_0816.JPG',
    category: 'Caps',
    linkName: 'fancy-crazy-faded-cap',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Flaming Blaze Design  Cap',
    image: '/cap_images/IMG_0789.JPG',
    category: 'Caps',
    linkName: 'flaming-blaze-design-cap',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 23,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '15',
    name: 'Plain Black Cap With Rings',
    image: '/cap_images/IMG_0792.JPG',
    category: 'Caps',
    linkName: 'plain-black-cap-with-rings',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '16',
    name: 'Daisy Washed Denim Cap In Grey',
    image: '/cap_images/IMG_0794.JPG',
    category: 'Caps',
    linkName: 'daisy-washed-denim-cap-in-grey',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '17',
    name: 'Crazy Design Orange Cap',
    image: '/cap_images/IMG_0798.JPG',
    category: 'Caps',
    linkName: 'crazy-design-orange-cap',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 4,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '18',
    name: 'White Cap With Blue Text Design',
    image: '/cap_images/IMG_0799.JPG',
    category: 'Caps',
    linkName: 'white-cap-with-blue-text-design',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 25,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '19',
    name: 'New Era Chicago Bulls Black Red Cap',
    image: '/cap_images/IMG_0801.JPG',
    category: 'Caps',
    linkName: 'new-era-chicago-bulls-black-red-cap',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 13,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '20',
    name: 'R Text Hat',
    image: '/cap_images/IMG_0803.JPG',
    category: 'Caps',
    linkName: 'r-text-hat',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '21',
    name: 'Mercedes-Benz Baseball Hat',
    image: '/cap_images/IMG_0807.JPG',
    category: 'Caps',
    linkName: 'mercedes-benz-baseball-hat',
    price: '6,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 9,
    rating: 4,
    numReviews: 12,
  },
]
export const tshirtItems = [
  {
    _id: '1',
    name: "Men's Contrast Color Stripe Printed Shirt",
    image: '/tshirt_images/IMG_1969.JPG',
    category: 'Tshirts',
    linkName: 'mens-contrast-color-stripe-printed-shirt',
    description: 'Easy wear with smooth texture',
    price: '17,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: "Men's Cotton Embroidered Casual Shirt",
    image: '/tshirt_images/IMG_1970.JPG',
    category: 'Tshirts',
    linkName: 'mens-cotton-embroidered-casual-shirt',
    description: 'Easy wear with smooth texture',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: "Men's Fashion Color Block Stripe Shirt",
    image: '/tshirt_images/IMG_1971.JPG',
    category: 'Tshirts',
    linkName: 'mens-fashion-color-block-stripe-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "Men's Carp Warrior Cat Print Japanese Shirt",
    image: '/tshirt_images/IMG_1972.JPG',
    category: 'Tshirts',
    linkName: 'mens-carp-warrior-cat-print-japanese-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,200',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Casual Color Block Loose Shirt",
    image: '/tshirt_images/IMG_1973.JPG',
    category: 'Tshirts',
    linkName: 'mens-casual-color-block-loose-shirt',
    description: 'Easy wear with smooth texture',
    price: '12,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Men's Hawaiian Shirt Apricot Vintage",
    image: '/tshirt_images/IMG_1974.JPG',
    category: 'Tshirts',
    linkName: 'mens-hawaiian-shirt-apricot-vintage',
    description: 'Easy wear with smooth texture',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Men's Asymmetric Tribal Printed Shirt",
    image: '/tshirt_images/IMG_1975.JPG',
    category: 'Tshirts',
    linkName: 'mens-asymmetric-tribal-printed-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '8',
    name: "Men's Front And Back Plum Blossom Shirt",
    image: '/tshirt_images/IMG_1976.JPG',
    category: 'Tshirts',
    linkName: 'mens-front-and-back-plum-blossom-shirt',
    description: 'Easy wear with smooth texture',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 12,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '9',
    name: "Men's Letter Geometric Print Patchwork Shirt",
    image: '/tshirt_images/IMG_1977.JPG',
    category: 'Tshirts',
    linkName: 'mens-letter-geometric-print-patchwork-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 8,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '10',
    name: "Men's Printed Shirt Button Down Short Sleeve",
    image: '/tshirt_images/IMG_1978.JPG',
    category: 'Tshirts',
    linkName: 'mens-printed-shirt-button-down-short-sleeve',
    description: 'Easy wear with smooth texture',
    price: '15,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '11',
    name: "Vintage Men's Shirt",
    image: '/tshirt_images/IMG_1979.JPG',
    category: 'Tshirts',
    linkName: 'vintage-mens-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 20,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '12',
    name: "Fancy Men's Designer Shirt",
    image: '/tshirt_images/IMG_1981.JPG',
    category: 'Tshirts',
    linkName: 'fancy-mens-designer-shirt',
    description: 'Easy wear with smooth texture',
    price: '15,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 17,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '13',
    name: "Men's Plaid Print Drawstring Hooded Overcoat",
    image: '/tshirt_images/IMG_1634.JPG',
    category: 'Tshirts',
    linkName: 'mens-plaid-print-drawstring-hooded-overcoat',
    description: 'Easy wear with smooth texture',
    price: '15,700',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '14',
    name: 'Vintage Flannel Shirt',
    image: '/tshirt_images/IMG_1638.JPG',
    category: 'Tshirts',
    linkName: 'vintage-flannel-shirt',
    description: 'Easy wear with smooth texture',
    price: '16,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '15',
    name: "Men's Tropical Plant Parrot Print Shirts",
    image: '/tshirt_images/IMG_2091.JPG',
    category: 'Tshirts',
    linkName: 'mens-tropical-plant-parrot-print-shirts',
    description: 'Easy wear with smooth texture',
    price: '16,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export const pantsItems = [
  {
    _id: '1',
    name: 'Drawstring Sweatpants',
    image: '/pant_images/IMG_0855.JPG',
    category: 'Pants',
    linkName: 'drawstring-sweatpants',
    price: '7,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 2,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Cargo Juggers',
    image: '/pant_images/IMG_0856.JPG',
    category: 'Pants',
    linkName: 'cargo-juggers',
    price: '8,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Custom Sweatpants',
    image: '/pant_images/IMG_0857.JPG',
    category: 'Pants',
    linkName: 'custom-sweatpants',
    price: '5,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Street Game Jeans',
    image: '/pant_images/IMG_0858.JPG',
    category: 'Pants',
    linkName: 'street-game-jeans',
    price: '15,200',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Washed Pocket Cargo Jeans",
    image: '/pant_images/IMG_0859.JPG',
    category: 'Pants',
    linkName: 'mens-washed-pocket-cargo-jeans',
    price: '12,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Men's Chrome Heart Blue Jeans",
    image: '/pant_images/IMG_0861.JPG',
    category: 'Pants',
    linkName: 'mens-chrome-heart-blue-jeans',
    price: '13,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Men's Chrome Heart Washed Grey Jeans",
    image: '/pant_images/IMG_0863.JPG',
    category: 'Pants',
    linkName: 'mens-chrome-heart-washed-grey-jeans',
    price: '7,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 3,
  },
  {
    _id: '8',
    name: 'Fancy Design Jeans',
    image: '/pant_images/IMG_0865.JPG',
    category: 'Pants',
    linkName: 'fancy-design-jeans',
    price: '7,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 12,
    rating: 4,
    numReviews: 2,
  },
]
export const setsItems = [
  {
    _id: '1',
    name: 'Drawstring Sweatpants Set',
    image: '/sets_images/IMG_2043.JPG',
    category: 'Sets',
    linkName: 'drawstring-sweatpants-set',
    description: 'Easy wear with smooth texture',
    price: '11,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: "Men's Lapel Neck Pocket Patched Shirt & Paisley Print Drawstring Waist Shorts",
    image: '/sets_images/IMG_2044.JPG',
    category: 'Sets',
    linkName:
      'mens-lapel-neck-pocket-patched-shirt-&-paisley-print-drawstring-waist-shorts',
    description: 'Easy wear with smooth texture',
    price: '8,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: "Men's Sets Stripe Black & White With Trouser",
    image: '/sets_images/IMG_2046.JPG',
    category: 'Sets',
    linkName: 'mens-sets-stripe-black-&-white-with-trouser',
    description: 'Easy wear with smooth texture',
    price: '15,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: "Men's Two Piece Outfits, Shirts & Shorts Sets",
    image: '/sets_images/IMG_2049.JPG',
    category: 'Sets',
    linkName: 'mens-two-piece-outfits-shirts-&-shorts-sets',
    description: 'Easy wear with smooth texture',
    price: '14,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Floral Print Shirt & Drawstring Waist Short Without Tee",
    image: '/sets_images/IMG_2051.JPG',
    category: 'Sets',
    linkName: 'mens-floral-print-shirt-&-drawstring-waist-short-without-tee',
    description: 'Easy wear with smooth texture',
    price: '14,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Men's Shirt & Drawstring Short Sets",
    image: '/sets_images/IMG_1966.JPG',
    category: 'Sets',
    linkName: 'mens-shirt-&-drawstring-short-sets',
    description: 'Easy wear with smooth texture',
    price: '14,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Men's Shirt with Shorts Sets",
    image: '/sets_images/IMG_2053.JPG',
    category: 'Sets',
    linkName: 'mens-shirt-with-shorts-sets',
    description: 'Easy wear with smooth texture',
    price: '10,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 4,
    numReviews: 3,
  },
  {
    _id: '8',
    name: "Men's Shirt with Shorts Sets",
    image: '/sets_images/IMG_1968.JPG',
    category: 'Sets',
    linkName: 'mens-shirt-with-shorts-sets',
    description: 'Easy wear with smooth texture',
    price: '10,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 4,
    numReviews: 3,
  },
]
export const newArrivals = [
  {
    _id: '1',
    name: 'Winnie Plisse Sweatshirt & Shorts Set',
    image: '/newarrivals_images/IMG_0769.JPG',
    category: 'New-Arrivals',
    linkName: 'winnie-plisse-sweatshirt-&-shorts-set',
    price: '18,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'LA Print Drawstring Hoodie',
    image: '/newarrivals_images/IMG_0925.JPG',
    category: 'New-Arrivals',
    linkName: 'la-print-drawstring-hoodie',
    price: '8,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Moutain Print & Rose Drawstring Hoodie',
    image: '/newarrivals_images/IMG_0926.JPG',
    category: 'New-Arrivals',
    linkName: 'mountain-print-&-rose-drawstring-hoodie',
    price: '8,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Island Cream Hawaiian Rayon Shirt',
    image: '/newarrivals_images/IMG_2058.JPG',
    category: 'New-Arrivals',
    linkName: 'island-cream-hawaiian-rayon-shirt',
    price: '10,500',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 0,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: "Men's Colorblock Shirt & Drawstring Waist Pants",
    image: '/newarrivals_images/IMG_2059.JPG',
    category: 'New-Arrivals',
    linkName: 'mens-colorblock-shirt-&-drawstring-waist-pants',
    price: '22,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: "Men's Lapel Collar Shirt With Drawstring Shorts Set",
    image: '/newarrivals_images/IMG_2060.JPG',
    category: 'New-Arrivals',
    linkName: 'mens-lapel-collar-shirt-with-drawstring-shorts-set',
    price: '25,000',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: "Men's Cartoon & Geo Print Shirt",
    image: '/newarrivals_images/IMG_2065.JPG',
    category: 'New-Arrivals',
    linkName: 'mens-cartoon-&-geo-print-shirt',
    price: '17,300',
    info: 'Tax included. Shipping calculated at checkout.',
    countInStock: 3,
    rating: 4,
    numReviews: 3,
  },
]
export const shortItems = []
